# Generated by Django 5.0.4 on 2024-04-16 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attendance", "0001_initial"),
        ("subject", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="subject.subject"
            ),
        ),
    ]
